#!/usr/bin/env python3
"""
Summary: Writes apps/meds/lib/starter_catalog.lua, the starter catalog as a Lua module.
         The Lua sandbox has no file access, so the catalog travels inside the app as a
         module that the app requires once, the first time it finds the catalog empty.
         tools/build_seed.py calls write_module with the entries it built.

This file is part of Medication Tracker
tools/starter_lua.py

Author(s): Gabriel Mongefranco
Created: 2026-10-03
Last Modified: 2026-10-03
Notes: See README file for documentation and full license information.

Copyright © 2026 Gabriel Mongefranco

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <https://www.gnu.org/licenses/>.
"""

import json
import os
import re

### Load Configuration ###
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE = os.path.join(ROOT, "apps", "meds", "lib", "starter_catalog.lua")

HEADER = """-- This file is part of Medication Tracker
-- apps/meds/lib/starter_catalog.lua
-- Author(s): Gabriel Mongefranco
-- Created: 2026-10-03
-- Last Modified: {date}
-- Summary: The starter catalog as a Lua table: one entry per record, each
--          {{ t = table, i = id, d = data }}, in the order the records are written.
--          Generated by tools/build_seed.py through tools/starter_lua.py; do not edit by hand.
-- Notes: See README file for documentation and full license information.
--
-- Copyright © 2026 Gabriel Mongefranco
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License along
-- with this program. If not, see <https://www.gnu.org/licenses/>.

return {{
"""

# A key that is a Lua name needs no quotes; any other key is bracketed.
PLAIN_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
# The record line the module writes, which tests and the smoke test read back.
RECORD_LINE = re.compile(r'^\{t="([^"]+)",i="([^"]+)",d=\{')


### Transform Records ###
def lua_string(text):
    """Quotes a string for Lua, escaping only what Lua needs."""
    escaped = (text.replace("\\", "\\\\").replace('"', '\\"')
               .replace("\n", "\\n").replace("\r", "\\r"))
    return '"' + escaped + '"'


def lua_value(value):
    """Writes one scalar as a Lua literal. A record holds no nested objects."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return json.dumps(value)
    if isinstance(value, str):
        return lua_string(value)
    raise ValueError("unsupported value in a record: %r" % type(value).__name__)


def lua_table(data):
    """Writes a flat object as a Lua table constructor, keys in a stable order."""
    parts = []
    for key in sorted(data):
        if data[key] is None:
            continue
        name = key if PLAIN_KEY.match(key) else "[" + lua_string(key) + "]"
        parts.append(name + "=" + lua_value(data[key]))
    return "{" + ",".join(parts) + "}"


def record_line(event):
    """One line of the module for one put event: {"tbl", "id", "d"} as a dictionary."""
    return "{t=%s,i=%s,d=%s},\n" % (
        lua_string(event["tbl"]), lua_string(event["id"]), lua_table(event["d"]))


### Save Results ###
def write_module(events, module_path, date):
    """Writes the module from put events, each a dictionary with tbl, id and d.
    Returns the number of records written. Raises ValueError for any other event."""
    count = 0
    with open(module_path, "w", encoding="utf-8") as target:
        target.write(HEADER.format(date=date))
        for event in events:
            if event.get("op", "put") != "put":
                raise ValueError("the starter catalog holds put events only")
            target.write(record_line(event))
            count += 1
        target.write("}\n")
    return count


def read_counts(module_path):
    """Counts the records of a written module by table, without running Lua."""
    counts = {}
    with open(module_path, encoding="utf-8") as source:
        for line in source:
            match = RECORD_LINE.match(line)
            if match:
                counts[match.group(1)] = counts.get(match.group(1), 0) + 1
    return counts
